apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekscluster-project
  region: ap-south-1

nodeGroups:
   - name: node1
     desiredCapacity: 2
     instanceType: t2.small
     ssh:
        publicKeyName: terraform-20200612192017563900000002
   - name: node2
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: terraform-20200612192017563900000002
   
#   - name: ng-mixed
  #   minSize: 2
    # maxSize: 5
     #instancesDistribution:
       #maxPrice: 0.017
       #instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
       #onDemandBaseCapacity: 0
       #onDemandPercentageAboveBaseCapacity: 50
       #spotInstancePools: 2     
     #ssh:
         #publicKeyName: mykey111222
